#!/bin/bash

# Cleanup script for the V-Model Regulatory Evidence smoke test
#
# Removes all runtime artifacts generated by setup.sh and run-test.sh.
# Safe to run between test invocations. Do NOT run while agents are active.
#
# What is removed:
#   - Agent processes (killed via pkill)
#   - Shared bare git origin (origin.git/)
#   - Shared runtime mailbox (runtime_mailbox/)
#   - Per-agent installed files (src/, dist/, node_modules/, etc.)
#   - Per-agent workspace and logs
#   - Shared workspace directory
#   - Test log files (*-test.log, smoke-run.log)
#
# What is preserved:
#   - config.template.json (per-agent tracked config template)
#   - README.md, setup.sh, run-test.sh, validate.sh, workflow.json
#   - This cleanup.sh script

set -eE
trap 'echo "FATAL: cleanup.sh failed at line $LINENO (exit $?)" >&2' ERR

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "================================================================"
echo "V-MODEL REGULATORY EVIDENCE SMOKE TEST -- CLEANUP"
echo "================================================================"
echo ""

# ----------------------------------------------------------------
# Kill agent processes
# ----------------------------------------------------------------
echo "Killing any running agent processes..."
pkill -f "node.*dist/index.js.*config.json" 2>/dev/null || true
sleep 1
pkill -9 -f "node.*dist/index.js.*config.json" 2>/dev/null || true
echo "  Done."

# ----------------------------------------------------------------
# Remove shared infrastructure
# ----------------------------------------------------------------
echo "Removing shared infrastructure..."
rm -rf runtime_mailbox
rm -rf origin.git
rm -rf workspace
rm -rf logs
echo "  Removed: runtime_mailbox/, origin.git/, workspace/, logs/"

# ----------------------------------------------------------------
# Clean per-agent runtime artifacts
# ----------------------------------------------------------------
echo "Cleaning per-agent runtime artifacts..."
for AGENT_DIR in ra developer qa manager; do
  if [ -d "${AGENT_DIR}/agent" ]; then
    rm -rf ${AGENT_DIR}/agent/src
    rm -rf ${AGENT_DIR}/agent/dist
    rm -rf ${AGENT_DIR}/agent/node_modules
    rm -rf ${AGENT_DIR}/agent/templates
    rm -rf ${AGENT_DIR}/agent/workspace
    rm -rf ${AGENT_DIR}/agent/logs
    rm -rf ${AGENT_DIR}/agent/mailbox
    rm -rf ${AGENT_DIR}/agent/.github
    rm -f  ${AGENT_DIR}/agent/package.json
    rm -f  ${AGENT_DIR}/agent/package-lock.json
    rm -f  ${AGENT_DIR}/agent/tsconfig.json
    rm -f  ${AGENT_DIR}/agent/config.json
    rm -f  ${AGENT_DIR}/agent/roles.json
    rm -f  ${AGENT_DIR}/agent/.npmrc
    rm -f  ${AGENT_DIR}/agent/jest.config.*
    rm -f  ${AGENT_DIR}/agent/*.md
    rm -f  ${AGENT_DIR}/agent/*.txt
    rm -f  ${AGENT_DIR}/agent/*.sh
    rm -f  ${AGENT_DIR}/agent/*.js
    echo "  Cleaned: ${AGENT_DIR}/agent/ (config.template.json preserved)"
  fi
done

# ----------------------------------------------------------------
# Remove log files
# ----------------------------------------------------------------
echo "Removing test log files..."
rm -f ra-test.log developer-test.log qa-test.log manager-test.log
rm -f smoke-run.log
echo "  Removed: *-test.log, smoke-run.log"

echo ""
echo "================================================================"
echo "Cleanup complete. Run ./setup.sh && ./run-test.sh to start fresh."
echo "================================================================"
