#!/bin/bash

# Setup script for workflow engine smoke test
#
# Uses the test harness CLI (scripts/smoke-test-cli.ts) to create
# mailbox directories and seed messages.  This ensures the test
# exercises the same code paths the agent uses at runtime -- if the
# message format, directory layout, or marker format changes in the
# source, the harness picks up the change automatically.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Resolve paths to the harness CLI and project root
HARNESS_ROOT="$(cd ../.. && pwd)"

# Ensure root-level dependencies are installed (smoke-test-cli imports from root src/)
if [ ! -d "${HARNESS_ROOT}/node_modules" ]; then
  echo "Installing root-level dependencies (first run)..."
  ( cd "${HARNESS_ROOT}" && npm install --silent 2>&1 | tail -5 )
fi

# CLI will be invoked via npx tsx after deps are installed
CLI=""  # set after npm install

echo "Setting up workflow engine smoke test..."
echo "This tests workflow classification, prompt injection, and transition routing."
echo ""

# Kill any leftover agent processes from previous runs
echo "Killing any leftover agent processes..."
pkill -f "node.*dist/index.js.*config.json" 2>/dev/null || true
sleep 1
pkill -9 -f "node.*dist/index.js.*config.json" 2>/dev/null || true

# Clean previous test artifacts
echo "Cleaning previous test artifacts..."
rm -rf developer/runtime_mailbox
rm -rf developer/agent/src developer/agent/dist developer/agent/node_modules
rm -rf developer/agent/package*.json developer/agent/tsconfig.json developer/agent/config.json
rm -rf developer/agent/workspace developer/agent/logs developer/agent/templates developer/agent/roles.json
rm -f test.log

# Copy source code from parent project (includes test-harness.ts)
echo "Copying source code..."
cp -r ../../src developer/agent/
cp -r ../../templates developer/agent/
cp ../../package.json developer/agent/
cp ../../tsconfig.json developer/agent/
cp ../../roles.json developer/agent/

# Copy config template to active config
echo "Setting up configuration..."
cp developer/agent/config.template.json developer/agent/config.json

# Install dependencies (needed before CLI can run)
echo "Installing dependencies..."
cd developer/agent
npm install
cd ../..

# Now that tsx is available, define the CLI command
# Run from the agent dir so tsx can resolve pino and other deps
CLI="npx --prefix developer/agent tsx ${HARNESS_ROOT}/scripts/smoke-test-cli.ts"

# Create mailbox structure using the harness
# This uses the same path conventions as MailboxManager.initialize()
echo "Creating mailbox structure..."
$CLI init-mailbox --base developer/runtime_mailbox --agent smoke-wf-dev --role developer
$CLI init-mailbox --base developer/runtime_mailbox --agent smoke-wf-mgr --role manager

# Seed workflow assignment message using the real packMessage() code path
echo "Seeding workflow assignment message..."
$CLI pack-workflow \
  --base developer/runtime_mailbox --agent smoke-wf-dev --role developer --queue normal \
  --workflow-id smoke-test-workflow \
  --task-id smoke-test-task-001 \
  --state IMPLEMENTING \
  --target-role developer \
  --prompt "Create a file called workflow_proof.txt in your workspace directory. The file must contain the text WORKFLOW_ENGINE_ACTIVE on its first line. This proves the workflow engine successfully delivered this task to you." \
  --from smoke-wf-mgr_manager \
  --to smoke-wf-dev_developer \
  --subject "Workflow Assignment: IMPLEMENTING"

echo ""
echo "Workflow engine smoke test setup complete!"
echo ""
echo "Test structure:"
echo "  - Developer agent with workflowFile configured"
echo "  - 1 packed WorkflowAssignment in normal mailbox (generated by harness CLI)"
echo "  - Manager mailbox ready to receive completion message"
echo "  - Workflow: IMPLEMENTING -> DONE (minimal 2-state)"
echo ""
echo "Or use the automated runner:"
echo "  ./run-test.sh"
